# Generated by Django 5.1.2 on 2024-11-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_news_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Layout Name')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Track Layout',
                'verbose_name_plural': 'Track Layouts',
            },
        ),
    ]
